package com.kim.kaziconnect.navigation

const val ROUT_SPLASH = "splash"
const val ROUT_ROLESELECTION = "roleselection"
const val ROUT_REGISTER = "register"
const val ROUT_LOGIN = "login"
const val ROUT_CLIENTGIG = "clientgig"
const val ROUT_CLIENTHOME = "clienthome"
const val ROUT_CLIENTMESSAGES = "clientmessages"
const val ROUT_CLIENTPROFILE = "clientprofile"
const val ROUT_FUNDIHOME = "fundihome"
const val ROUT_FUNDIJOB = "fundijob"
const val ROUT_FUNDIPROFILE = "fundiprofile"
const val ROUT_FUNDIMESSAGES = "fundimessages"
const val ROUT_CLIENTNOTIFICATION = "clientnotification"
const val ROUT_FUNDINOTIFICATION = "fundinotification"
const val ROUT_JOBDETAILS = "jobdetails"
const val ROUT_JOBDETAILS_NOAPPLY = "jobdetails_noapply"
const val ROUT_POSTJOB = "postjob"
const val ROUT_APPLICANTSLIST = "applicantslist"